name: Build Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build ARM64 Debug APK
        run: ./gradlew :app:assembleArm64Debug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Portal-ARM64-Debug
          path: app/build/outputs/apk/arm64/debug/*.apk
          if-no-files-found: error
